---
deployment:
  tasks:
    - export DEPLOYPATH=/home/coliakfm/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp Style $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp images $DEPLOYPATH
    - /bin/cp Pages $DEPLOYPATH